version = 0

[[process]]
name = "css"
command = "bunx @tailwindcss/cli -i ./src/index.css -o ./src/output.css --watch"

[[process]]
name = "server"
command = "bun --hot src/index.ts"
deps = [{ name = "css", condition = "started" }]
