version = 0

[[process]]
name = "api"
command = "bun --hot ./src/index.ts"
env = { BLOSSOM_DIR = ".blossom-dev" }

[process.readiness_probe]
type = "http"
host = "localhost"
port = 3000
path = "/api/status"

[[process]]
name = "vite"
command = "bun vite"
env = { BLOSSOM_DIR = ".blossom-dev" }
deps = [{ name = "api", condition = "ready" }]
